---
#引入PHP运行环境元数据，并初始化
- include_vars: roles/role_php/vars/php_runtime_meta.yml

#Modify var for this playbook
- set_fact:
    opencart_vhost_dir: "{{php_runtime_meta[ansible_os_family][opencart_webs].vhost_dir}}"
    opencart_vhost_src: "{{php_runtime_meta[ansible_os_family][opencart_webs].vhost_src}}"
    opencart_service: "{{php_runtime_meta[ansible_os_family][opencart_webs].service}}"
    opencart_owner: "{{php_runtime_meta[ansible_os_family][opencart_webs].owner}}"
    opencart_db_password: "{{mysql_root_password}}"

- debug:
    msg: runtime {{ opencart_vhost_dir }}, {{opencart_vhost_src}}, {{opencart_service}}, {{opencart_owner}}, {{opencart_webs}}, {{ansible_distribution}}

# Opencart
- name: Remove extra dir
  shell: rm -rf /data/wwwroot/*{{opencart_name}}*

- name: Create folder /data/wwwroot/{{opencart_name}}
  file:
    path: /data/wwwroot/{{opencart_name}}
    state: directory

- name: Get OpenCart from {{opencart_distribution_meta[opencart_distribution].download_url}}
  unarchive:
    src: "{{opencart_distribution_meta[opencart_distribution].download_url}}"
    dest: /data/wwwroot/{{opencart_name}}
    remote_src: yes

- name: Rename opencart folder for many times re-installation
  shell: cd /data/wwwroot; if [ ! -d "{{opencart_name}}" ]; then mv *{{opencart_name}}* {{opencart_name}}; fi

- name: Rename config-dist.php to config.php
  shell: |
    cp /data/wwwroot/opencart/upload/config-dist.php /data/wwwroot/opencart/upload/config.php
    cp /data/wwwroot/opencart/upload/admin/config-dist.php /data/wwwroot/opencart/upload/admin/config.php
  when: opencart_distribution == "original"

# 系统通用
- name: Permission directory
  shell: |
     find /data/wwwroot -type d -exec chmod 750 {} \;
     find /data/wwwroot -not -type d -exec chmod 640 {} \;

# 根据不同的基础环境分别处理
- block:

  - name: Copy Apache or Nginx vhost configuration
    template: src={{opencart_vhost_src}} dest={{opencart_vhost_dir}}

  - name: change owner&group
    shell: chown -R {{opencart_owner}}:{{opencart_owner}} /data/wwwroot
    
  - name: restart Apache or Nginx
    service: name={{opencart_service}} state=restarted enabled=yes

  - name: restart php-fpm
    service: name=php-fpm state=restarted

- name: Check opencart version
  shell: >
    sudo echo "opencart version:" $(cat /data/wwwroot/opencart/upload/admin/index.php  |grep VERSION |cut -d"'" -f4) |sudo tee -a /data/logs/install_version.txt  